# Generated by Django 2.2.6 on 2019-10-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0002_auto_20191030_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=264, unique=True),
        ),
    ]
