# Generated by Django 2.2.6 on 2019-11-02 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0003_auto_20191030_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
